# Generated by Django 4.2.6 on 2024-11-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6, verbose_name='공시 제출월')),
                ('fin_co_no', models.CharField(max_length=10, verbose_name='금융회사 코드')),
                ('fin_prdt_cd', models.CharField(max_length=50, verbose_name='금융상품 코드')),
                ('kor_co_nm', models.CharField(max_length=100, verbose_name='금융회사명')),
                ('fin_prdt_nm', models.CharField(max_length=100, verbose_name='금융상품명')),
                ('join_way', models.CharField(max_length=100, verbose_name='가입방법')),
                ('mtrt_int', models.TextField(verbose_name='만기 후 이자율')),
                ('spcl_cnd', models.TextField(verbose_name='우대조건')),
                ('join_deny', models.CharField(max_length=1, verbose_name='가입제한')),
                ('join_member', models.TextField(verbose_name='가입대상')),
                ('etc_note', models.TextField(verbose_name='기타사항')),
                ('max_limit', models.IntegerField(blank=True, null=True, verbose_name='최대한도')),
                ('dcls_strt_day', models.CharField(max_length=8, verbose_name='공시 시작일')),
                ('dcls_end_day', models.CharField(blank=True, max_length=8, null=True, verbose_name='공시 종료일')),
                ('fin_co_subm_day', models.CharField(max_length=12, verbose_name='금융회사 제출일')),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.CharField(max_length=20)),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.CharField(max_length=1)),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
                ('max_limit', models.BigIntegerField(null=True)),
                ('dcls_strt_day', models.CharField(max_length=8)),
                ('dcls_end_day', models.CharField(max_length=8, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type', models.TextField()),
                ('intr_rate', models.FloatField()),
                ('save_trm', models.IntegerField()),
                ('intr_rate_type_nm', models.TextField()),
                ('intr_rate2', models.FloatField()),
                ('rsrv_type', models.TextField()),
                ('rsrv_type_nm', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finlife.savingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6, verbose_name='공시 제출월')),
                ('fin_co_no', models.CharField(max_length=10, verbose_name='금융회사 코드')),
                ('fin_prdt_cd', models.CharField(max_length=50, verbose_name='금융상품 코드')),
                ('intr_rate_type', models.CharField(max_length=1, verbose_name='금리유형')),
                ('intr_rate_type_nm', models.CharField(max_length=10, verbose_name='금리유형명')),
                ('save_trm', models.CharField(max_length=3, verbose_name='저축기간')),
                ('intr_rate', models.FloatField(blank=True, null=True, verbose_name='기본금리')),
                ('intr_rate2', models.FloatField(blank=True, null=True, verbose_name='우대금리')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='finlife.depositproduct')),
            ],
        ),
    ]
