# Generated by Django 4.2.6 on 2024-11-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='연령대 점수'),
        ),
        migrations.AddField(
            model_name='user',
            name='consumption_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='소비습관 점수'),
        ),
        migrations.AddField(
            model_name='user',
            name='financial_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='금융성향 점수'),
        ),
        migrations.AddField(
            model_name='user',
            name='income_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='소득수준 점수'),
        ),
        migrations.AddField(
            model_name='user',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='테스트 진행일'),
        ),
    ]
