# Generated by Django 4.2.16 on 2024-11-20 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_agreement_date_user_birth_date_user_member_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agreement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('regular', '일반회원'), ('expert', '전문가회원')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
